dist: trusty # jdk 8 not available on xenial
language: java

jdk:
  - openjdk8

# Replace Travis's default Maven installation step with a no-op.
# This avoids redundantly pre-running 'mvn install -DskipTests' every time.
install: true

# Replace Travis's default build step.
# Only run the test suite
script:  mvn clean verify --settings maven-settings.xml -B -V -Dgpg.skip

# if on ibi-dev branch, then upload docs to IBI s3 buckets & cloudfront
after_success:
  - |
    if [[ "$TRAVIS_BRANCH" = "ibi-dev" ]]; then
      # create AWS deploy credentials
      mkdir ~/.aws && printf '%s\n' '[default]' 'aws_access_key_id=${AWS_ACCESS_KEY_ID}' 'aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}' 'region=us-east-1' > ~/.aws/config;
      # build markdown docs using mkdocs
      mkdocs build
      # build enunciate and JavaDoc
      mvn -DskipTests site
      # copy enunciate API docs into mkdocs folder
      cp -R target/site/enunciate/apidocs target/mkdocs/api
      # copy JavaDoc into mkdocs folder
      cp -R target/apidocs target/mkdocs/JavaDoc
      # upload to S3
      aws s3 cp --recursive --acl public-read "target/mkdocs" "s3://otp-docs.ibi-transit.com"
    fi


# Secure envs are OSSRH_JIRA_USERNAME, OSSRH_JIRA_PASSWORD, GPG_KEY_NAME, GPG_PASSPHRASE
env:
  global:
    - JAVA_OPTS=-Xmx2g

# If sudo is disabled, CI runs on container based infrastructure (allows caching &c.)
sudo: false

# Retain the local Maven repository to speed up builds.
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
before_install:
  # install mkdocs
  - pip install --user mkdocs
  # install awscli
  - pip install --user awscli

notifications:
  email: false
  # Notify us of the build status on MS Teams
  webhooks: https://outlook.office.com/webhook/03fa4a79-572f-4c68-b756-e4e851d0215a@9093f1a3-8771-4fb7-8596-d51eeef18cda/TravisCI/0aec73ecb8eb4ad696ea27dd3c6a102d/286c079f-6085-4aa0-8f8d-e2a3e8d1f568
before_deploy:
  # Get branch name of current branch for use in jar name: https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  # Copy shaded jar over to deploy dir as git-described jar (either version or version+commit) and branch-specific jar.
  - mkdir deploy
  - cp target/*-shaded.jar deploy/otp-$(git describe --always).jar
  - cp target/*-shaded.jar deploy/otp-latest-$BRANCH.jar
deploy:
  provider: s3
  access_key_id: AKIA2YG5XQ2YDBGQMBSN
  secret_access_key:
    secure: aIDBpMyoSAohVq5TP3U4sYDTO2G4LeKuf8SJxmGCjDlohNRNQTqXHhjh8hlp7u9kwMPNuYuk/SqX0JYI9jIaUNDmEYcjfYcTm8BP+TF4ITwO7yDUvAXfOrRo9BprFvTWd+NW8946bZzkoNJB2hfYoUrB0HFb0yLOzVyG5He/V8qkFBf99eeSYMn3/nbBEjoSm5jVXQNuw/LqT4XA0O3AwHRWrKRoOYAfYk2L5MmQjbq/UnCUEjBHSDw4QBv3BCSjmEHv7KSlg5b1puFz+AeZiLsLFVxvJlJbtmBfeDnr3xGYjTVvJIdDN7ExF8udQ0ZuJG9uD8ObArzYwOw051uJOz5JRW3ldXQp0MSvhKephjjv1ezAc3Nw9B8oOCwrRdGK0ns2i9gGANBf19L9aYPGPsir6pdZu2uGvc0ryLIoUmtP0TK9xO3bInYCgnmdSsDcvjmZAzBwBmGE+50sorYb2r569AqH7eQ5q0T46hn1tyXE1oNW6KZRd/pZflZA4WC1KK522dHshgHnksDpsTHnax1SSkbLInnhUqcBI9u0EJ0ECDzJwRrAlXxqO1qGllLxR8vfVz7ORq7kfDOgKUj4CnWIAW6nsc9GeGcN+x4Ihbroed+DIyneieSzp8Z8iy/94pQqrE1Q0xt9akyxFKYlGg2YHO+otVhU9+3WKNWRKnI=
  bucket: otp-repo
  local-dir: deploy
  acl: public_read
  skip_cleanup: true
  on:
    repo: ibi-group/OpenTripPlanner
    all_branches: true
